<a href="https://colab.research.google.com/github/ayushipradhan30/DMDW-Lab-Assignment/blob/main/DMDW_Lab2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from scipy import stats
import pandas as pd

In [4]:
d=pd.read_csv(r"https://raw.githubusercontent.com/anshupandey/Machine_Learning_Training/master/datasets/regiment.csv")
d

index    regiment company      name  preTestScore  postTestScore
0       0  Nighthawks     1st    Miller             4             25
1       1  Nighthawks     1st  Jacobson            24             94
2       2  Nighthawks     2nd       Ali            31             57
3       3  Nighthawks     2nd    Milner             2             62
4       4    Dragoons     1st     Cooze             3             70
5       5    Dragoons     1st     Jacon             4             25
6       6    Dragoons     2nd    Ryaner            24             94
7       7    Dragoons     2nd      Sone            31             57
8       8      Scouts     1st     Sloan             2             62
9       9      Scouts     1st     Piger             3             70
10     10      Scouts     2nd     Riani             2             62
11     11      Scouts     2nd       Ali             3             70

In [5]:
d.shape

(12, 6)

In [6]:
d.head()

index    regiment company      name  preTestScore  postTestScore
0      0  Nighthawks     1st    Miller             4             25
1      1  Nighthawks     1st  Jacobson            24             94
2      2  Nighthawks     2nd       Ali            31             57
3      3  Nighthawks     2nd    Milner             2             62
4      4    Dragoons     1st     Cooze             3             70

In [7]:
d.tail()

index  regiment company   name  preTestScore  postTestScore
7       7  Dragoons     2nd   Sone            31             57
8       8    Scouts     1st  Sloan             2             62
9       9    Scouts     1st  Piger             3             70
10     10    Scouts     2nd  Riani             2             62
11     11    Scouts     2nd    Ali             3             70

In [8]:
d.info

<bound method DataFrame.info of     index    regiment company      name  preTestScore  postTestScore
0       0  Nighthawks     1st    Miller             4             25
1       1  Nighthawks     1st  Jacobson            24             94
2       2  Nighthawks     2nd       Ali            31             57
3       3  Nighthawks     2nd    Milner             2             62
4       4    Dragoons     1st     Cooze             3             70
5       5    Dragoons     1st     Jacon             4             25
6       6    Dragoons     2nd    Ryaner            24             94
7       7    Dragoons     2nd      Sone            31             57
8       8      Scouts     1st     Sloan             2             62
9       9      Scouts     1st     Piger             3             70
10     10      Scouts     2nd     Riani             2             62
11     11      Scouts     2nd       Ali             3             70>

In [10]:
d.describe()

index  preTestScore  postTestScore
count  12.000000     12.000000      12.000000
mean    5.500000     11.083333      62.333333
std     3.605551     12.324833      21.376850
min     0.000000      2.000000      25.000000
25%     2.750000      2.750000      57.000000
50%     5.500000      3.500000      62.000000
75%     8.250000     24.000000      70.000000
max    11.000000     31.000000      94.000000

In [11]:
d.duplicated().sum()

0

In [12]:
d.isnull().sum()

index            0
regiment         0
company          0
name             0
preTestScore     0
postTestScore    0
dtype: int64

In [13]:
#numpy

In [16]:
ar=[int(i) for i in input().split()]
ar=np.array(ar)
ar

1 2 3 4 5 6


array([1, 2, 3, 4, 5, 6])

In [17]:
print(np.__version__)

1.18.5


In [18]:
print(type(ar))

<class 'numpy.ndarray'>


In [19]:
#tuple
ar=np.array((1,2,3,4))
ar

array([1, 2, 3, 4])

In [20]:
#create 0-D array
a=np.array(10)
a

array(10)

In [21]:
#create 1-D array
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [22]:
#create a 2-D array
a=np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [23]:
#create a 3-D array
arr= np.array([[[1, 2, 1], [4, 5, 2]], [[1, 2, 3], [9, 5, 6]]])
print(arr)

[[[1 2 1]
  [4 5 2]]

 [[1 2 3]
  [9 5 6]]]


In [24]:
#check number of dimensions
a=np.array(10)
b=np.array([1,2,3,4,5])
c=np.array([[1, 2, 3], [4, 5, 6]])
d=np.array([[[1, 2, 1], [4, 5, 2]], [[1, 2, 3], [9, 5, 6]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [25]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('print 3 rd element of 1stdim', arr[0, 3])

print 3 rd element of 1stdim 4


In [26]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


In [27]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5:2])

[2 4]


In [28]:
arr = np.array(['apple', 'banana', 'cherry'])
print(arr.dtype)

<U6
