<a href="https://colab.research.google.com/github/ayushipradhan30/DMDW-Lab-Assignment/blob/main/DMDW_Lab2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from scipy import stats
import pandas as pd

In [ ]:
d=pd.read_csv(r"https://raw.githubusercontent.com/anshupandey/Machine_Learning_Training/master/datasets/regiment.csv")
d

index    regiment company      name  preTestScore  postTestScore
0       0  Nighthawks     1st    Miller             4             25
1       1  Nighthawks     1st  Jacobson            24             94
2       2  Nighthawks     2nd       Ali            31             57
3       3  Nighthawks     2nd    Milner             2             62
4       4    Dragoons     1st     Cooze             3             70
5       5    Dragoons     1st     Jacon             4             25
6       6    Dragoons     2nd    Ryaner            24             94
7       7    Dragoons     2nd      Sone            31             57
8       8      Scouts     1st     Sloan             2             62
9       9      Scouts     1st     Piger             3             70
10     10      Scouts     2nd     Riani             2             62
11     11      Scouts     2nd       Ali             3             70

In [ ]:
d.shape

(12, 6)

In [ ]:
d.head()

index    regiment company      name  preTestScore  postTestScore
0      0  Nighthawks     1st    Miller             4             25
1      1  Nighthawks     1st  Jacobson            24             94
2      2  Nighthawks     2nd       Ali            31             57
3      3  Nighthawks     2nd    Milner             2             62
4      4    Dragoons     1st     Cooze             3             70

In [ ]:
d.tail()

index  regiment company   name  preTestScore  postTestScore
7       7  Dragoons     2nd   Sone            31             57
8       8    Scouts     1st  Sloan             2             62
9       9    Scouts     1st  Piger             3             70
10     10    Scouts     2nd  Riani             2             62
11     11    Scouts     2nd    Ali             3             70

In [ ]:
d.info

<bound method DataFrame.info of     index    regiment company      name  preTestScore  postTestScore
0       0  Nighthawks     1st    Miller             4             25
1       1  Nighthawks     1st  Jacobson            24             94
2       2  Nighthawks     2nd       Ali            31             57
3       3  Nighthawks     2nd    Milner             2             62
4       4    Dragoons     1st     Cooze             3             70
5       5    Dragoons     1st     Jacon             4             25
6       6    Dragoons     2nd    Ryaner            24             94
7       7    Dragoons     2nd      Sone            31             57
8       8      Scouts     1st     Sloan             2             62
9       9      Scouts     1st     Piger             3             70
10     10      Scouts     2nd     Riani             2             62
11     11      Scouts     2nd       Ali             3             70>

In [ ]:
d.describe()

index  preTestScore  postTestScore
count  12.000000     12.000000      12.000000
mean    5.500000     11.083333      62.333333
std     3.605551     12.324833      21.376850
min     0.000000      2.000000      25.000000
25%     2.750000      2.750000      57.000000
50%     5.500000      3.500000      62.000000
75%     8.250000     24.000000      70.000000
max    11.000000     31.000000      94.000000

In [ ]:
d.duplicated().sum()

0

In [ ]:
d.isnull().sum()

index            0
regiment         0
company          0
name             0
preTestScore     0
postTestScore    0
dtype: int64

In [ ]:
#numpy

In [ ]:
ar=[int(i) for i in input().split()]
ar=np.array(ar)
ar

1 2 3 4 5 6


array([1, 2, 3, 4, 5, 6])

In [ ]:
print(np.__version__)

1.18.5


In [ ]:
print(type(ar))

<class 'numpy.ndarray'>


In [ ]:
#tuple
ar=np.array((1,2,3,4))
ar

array([1, 2, 3, 4])

In [ ]:
#create 0-D array
a=np.array(10)
a

array(10)

In [ ]:
#create 1-D array
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [ ]:
#create a 2-D array
a=np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [ ]:
#create a 3-D array
arr= np.array([[[1, 2, 1], [4, 5, 2]], [[1, 2, 3], [9, 5, 6]]])
print(arr)

[[[1 2 1]
  [4 5 2]]

 [[1 2 3]
  [9 5 6]]]


In [ ]:
#check number of dimensions
a=np.array(10)
b=np.array([1,2,3,4,5])
c=np.array([[1, 2, 3], [4, 5, 6]])
d=np.array([[[1, 2, 1], [4, 5, 2]], [[1, 2, 3], [9, 5, 6]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [ ]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('print 3 rd element of 1stdim', arr[0, 3])

print 3 rd element of 1stdim 4


In [ ]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5:2])

[2 4]


In [ ]:
arr = np.array(['apple', 'banana', 'cherry'])
print(arr.dtype)

<U6


In [29]:
#pandas

In [30]:
data=[1,2,3,4,5]
df=pd.DataFrame(data)
df

0
0  1
1  2
2  3
3  4
4  5

In [31]:
data=[['A',10],['B',15],['C',20]]
df=pd.DataFrame(data)
df

0   1
0  A  10
1  B  15
2  C  20

In [32]:
ser = pd.Series([1, 3, 5, np.nan, 6, 8])
ser

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [33]:
d = pd.date_range('20130101', periods=6)
d

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')

In [34]:
df = pd.DataFrame(np.random.randn(6, 4), index=d, columns=list('abcd'))
df

a         b         c         d
2013-01-01  0.511123 -0.251303 -0.190522  0.265606
2013-01-02 -0.084340 -0.619737 -1.637643  1.200103
2013-01-03 -0.340120 -0.682510  0.831811 -0.709176
2013-01-04 -0.808195  1.318129 -0.394419  0.630913
2013-01-05  1.362936 -1.400859 -0.260543 -0.837696
2013-01-06 -1.187821 -0.117590  0.117231 -0.986124

In [35]:
df2 = pd.DataFrame({'A': 1.,'B': pd.Timestamp('20130102'),'C': pd.Series(1, index=list(range(4)), dtype='float32'),'D': np.array([3] * 4, dtype='int32'),'E': pd.Categorical(["test", "train", "test", "train"]),'F': 'foo'})
df2

A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo

In [36]:
df.tail(3)

a         b         c         d
2013-01-04 -0.808195  1.318129 -0.394419  0.630913
2013-01-05  1.362936 -1.400859 -0.260543 -0.837696
2013-01-06 -1.187821 -0.117590  0.117231 -0.986124

In [37]:
df.index

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')

In [38]:
df.columns

Index(['a', 'b', 'c', 'd'], dtype='object')

In [39]:
df.to_numpy()

array([[ 0.51112301, -0.25130269, -0.19052247,  0.26560563],
       [-0.08433982, -0.61973721, -1.63764289,  1.2001034 ],
       [-0.34011999, -0.68250991,  0.83181052, -0.70917587],
       [-0.80819547,  1.31812895, -0.39441894,  0.63091299],
       [ 1.36293586, -1.40085896, -0.26054283, -0.83769562],
       [-1.18782079, -0.11758986,  0.11723109, -0.98612372]])

In [40]:
df2.to_numpy()

array([[1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'train', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'train', 'foo']],
      dtype=object)

In [41]:
df2.describe()

A    C    D
count  4.0  4.0  4.0
mean   1.0  1.0  3.0
std    0.0  0.0  0.0
min    1.0  1.0  3.0
25%    1.0  1.0  3.0
50%    1.0  1.0  3.0
75%    1.0  1.0  3.0
max    1.0  1.0  3.0

In [42]:
df.describe()

a         b         c         d
count  6.000000  6.000000  6.000000  6.000000
mean  -0.091070 -0.292312 -0.255681 -0.072729
std    0.922602  0.907091  0.806850  0.900468
min   -1.187821 -1.400859 -1.637643 -0.986124
25%   -0.691177 -0.666817 -0.360950 -0.805566
50%   -0.212230 -0.435520 -0.225533 -0.221785
75%    0.362257 -0.151018  0.040293  0.539586
max    1.362936  1.318129  0.831811  1.200103

In [43]:
df.T

2013-01-01  2013-01-02  2013-01-03  2013-01-04  2013-01-05  2013-01-06
a    0.511123   -0.084340   -0.340120   -0.808195    1.362936   -1.187821
b   -0.251303   -0.619737   -0.682510    1.318129   -1.400859   -0.117590
c   -0.190522   -1.637643    0.831811   -0.394419   -0.260543    0.117231
d    0.265606    1.200103   -0.709176    0.630913   -0.837696   -0.986124